[package]
name = "manga-reader-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
fantoccini = "0.21.2"
futures-util = "0.3.31"
image = "0.25.5"
reqwest = "0.12.9"
serde_json = "1.0.132"
thiserror = "2.0.1"
tokio = { version = "1.41.1", features = ["full"] }
